# Setup
title:        Data Science Glossary
tagline:      A Glossary of Data Science, Statistics, Machine Learning, and Artificial Intelligence.
baseurl:      ""
paginate:     1
locale:       "en"
permalink: /:categories/:title
url: "http://www.dsglossary.com"
repository: ryanleeallred/ryanleeallred.github.io

#Organize Category Collections
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# About/contact
author:
  name:       Ryan Allred
  url:        http://twitter.com/ryanallred

#Others
markdown: kramdown

# Gems / Plugins
plugins: 
  - jekyll-sitemap
  - "jekyll-github-metadata"
  - jekyll-paginate




#API Calls

# jekyll_get:
#   - data: contributors
#     json: 'https://18f.gsa.gov/hub/api/team/'