# Setup
title:        Data Science Glossary
tagline:      A Glossary of Data Science, Statistics, Machine Learning, and Artificial Intelligence.
baseurl:      ""
paginate:     1
locale:       "en"
permalink: /:categories/:title

#Organize Category Collections
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# About/contact
author:
  name:       Ryan Allred
  url:        http://twitter.com/ryanallred

# Gems
# gems:
#   - jekyll-paginate

#Others
markdown: kramdown

#API Calls

# jekyll_get:
#   - data: contributors
#     json: 'https://18f.gsa.gov/hub/api/team/'