# Setup
title:        Data Science Glossary
tagline:      A Glossary of Data Science, Statistics, Machine Learning, and Artificial Intelligence
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Ryan allred
  url:        http://www.dsglossary.com/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
